[tool.poetry]
name = "gym-pybullet-drones-routing"
version = "1.0.0"
description = "DRL-based collision avoidance for limited-sensing UAS using PyBullet simulation"
authors = ["Komsun Tamanakijprasart"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "gym_pybullet_drones" },
    { include = "training" }
]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.24"
scipy = "^1.10"
transforms3d = "^0.4.1"
matplotlib = "^3.7"
pytest = "^7.3"
pybullet = "^3.2.5"
gymnasium = "^0.28"
torch = "^2.0"
pyyaml = "^6.0"
tensorboard = "^2.14"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
